services:
  robotic-manipulators:
    image: thiagolages/robotic-manipulators:latest
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # GUI sharing
      - ./src:/home/comau/robotic-manipulators/src
      - ./data:/home/comau/robotic-manipulators/data
    # entrypoint: ["/bin/bash", "-l", "-c", "sleep infinity"]
    command: /home/comau/command.sh
    environment:
      DISPLAY:
      QT_X11_NO_MITSHM: 1
      PYTHONUNBUFFERED: 1
      TERM: xterm-256color
    hostname: smart-six
    container_name: robotic-manipulators
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
